[[regexes]]
regex = '(.*) >>> (.*)'
style = { fg = "red", bold = true }

[[keywords]]
words = ['INFO', 'info']
style = { fg = "green" }

[[keywords]]
words = ['WARNING', 'warning']
style = { fg = "yellow" }

[[keywords]]
words = ['ERROR', 'error']
style = { fg = "red" }

[[keywords]]
words = ['offset', 'Offset', 'OFFSET']
style = { fg = "blue" }

[[keywords]]
words = ['CfgWr0', 'CfgRd0', 'MemRd', 'MemWr']
style = { fg = "yellow" }

[[keywords]]
words = ['Payload']
style = { fg = "magenta" }

[[regexes]]
regex = '(.*) Status == UR (.*)'
style = { fg = "red", bold = true }

[[keywords]]
words = ['IO_PORT']
style = { bold = true }

[[regexes]]
regex = '\[(.*)\]'
style = { fg = "bright_white" }
