typeset -U path
path=(/sbin $path)
path=(/usr/sbin $path)
path=($(python3 -m site --user-base)/bin $path)
path=(/snap/bin $path)
path=(/home/adrien/.bin $path)
path=(/home/adrien/.cargo/bin $path)

eval $(keychain --eval --quiet acharruel)

# android-studio
path=(/usr/local/android-studio/bin $path)
export _JAVA_AWT_WM_NONREPARENTING=1
