format = """
$time\
$username\
$hostname\
$directory\
$git_branch\
$line_break\
$python\
$character"""

command_timeout = 1000

[directory]
style = "blue bold"
fish_style_pwd_dir_length = 1

[character]
success_symbol = "[❯](yellow bold)"
error_symbol = "[❯](red bold)"
vimcmd_symbol = "[❮](purple bold)"

[git_branch]
format = "[ $branch ]($style)"
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "red"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[time]
disabled = false
format = '[$time]($style) '
style = "bright-cyan bold"
time_format = '%H:%M'

[username]
disabled = false
show_always = false
style_user = "red bold"
format = '[$user]($style)'

[hostname]
ssh_only = true
format = '@[$hostname]($style) '
style = "green"
