# UI #
osc=no
osd-bar=yes
osd-bar-h=2
osd-bar-align-x=-0
osd-bar-align-y=-0.1
osd-font=Segoe UI
osd-font-size=26
osd-bar-w=90

# Video #
vo=gpu-next
gpu-api=d3d11
hwdec=auto-d3d11va-copy
profile=gpu-hq

scale=ewa_lanczossharp
cscale=ewa_lanczossharp
dscale=mitchell

deband=yes
deband-iterations=2
deband-threshold=35
deband-range=16
deband-grain=5


# Color #
icc-profile-auto=yes
target-colorspace-hint=yes

# Audio #
ao=wasapi
audio-exclusive=no
volume-max=150

# Language #
alang=eng,en
slang=eng,en

# Subtitles Loading / Style #
sub-auto=fuzzy
sub-font="C:/Windows/Fonts/arial.ttf"
sub-font-size=38
sub-scale=1.0
sub-border-size=1
sub-shadow-offset=1
sub-shadow-color=0.0/0.0/0.0/0.7

# Subtitles Position #
sub-use-margins=no
sub-align-y=bottom
sub-margin-y=40

# Playback / comfort #
save-position-on-quit=yes
stop-screensaver=yes
volume=70

# Screenshots #
screenshot-format=png
screenshot-directory=~/Pictures/mpv

# Cache #
cache=yes
demuxer-max-bytes=200MiB
demuxer-max-back-bytes=100MiB
