# Sway startup programs

# startup programs
exec nm-applet --indicator
exec blueman-applet
exec udiskie &

exec google-chrome
exec steam

assign [class="^Google-chrome$"] → 1
assign [class="^Steam"] → 2
