# Hide clutter #
showtitle=yes
volumecontrol=no
showjump=yes

# Faster hide #
hidetimeout=800
fadeduration=200

# Smaller seek handle #
seekbarhandlesize=0.3

# Keep UI on pause #
showonpause=yes
